name: Check formatting
on:
  workflow_call:
    inputs:
      python_v:
        description: "Python version needed to run the code, eg. 3.10.6"
        default: 3.10.6
        required: false
        type: string

jobs:
  format:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        - name: Set up Python ${{ inputs.python_v }}
          uses: actions/setup-python@v5
          with:
              python-version: ${{ inputs.python_v }}
        - name: Install pre-commit
          run: |
            python -m pip install --upgrade pip
            pip install pre-commit==3.8.0
            pre-commit install
        - name: Run pre-commit (all files)
          run: |
            if test -f ".pre-commit-config.yaml"
            then
              pre-commit run --all-files --show-diff-on-failure
            else
              echo "::warning::No pre-commit config available"
            fi
